//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.18 at 05:54:38 PM GMT 
//


package com.dimensiondata.cloud.client.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AntiAffinityNetworkInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AntiAffinityNetworkInfoType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="nic"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="privateIpv4" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="networkId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="networkName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="macAddress" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="state" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="networkInfo"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="primaryNic" type="{urn:didata.com:api:cloud:types}NicType"/&gt;
 *                   &lt;element name="additionalNic" type="{urn:didata.com:api:cloud:types}NicType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attribute name="networkDomainId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="networkDomainName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AntiAffinityNetworkInfoType", propOrder = {
    "nic",
    "networkInfo"
})
public class AntiAffinityNetworkInfoType {

    protected AntiAffinityNetworkInfoType.Nic nic;
    protected AntiAffinityNetworkInfoType.NetworkInfo networkInfo;

    /**
     * Gets the value of the nic property.
     * 
     * @return
     *     possible object is
     *     {@link AntiAffinityNetworkInfoType.Nic }
     *     
     */
    public AntiAffinityNetworkInfoType.Nic getNic() {
        return nic;
    }

    /**
     * Sets the value of the nic property.
     * 
     * @param value
     *     allowed object is
     *     {@link AntiAffinityNetworkInfoType.Nic }
     *     
     */
    public void setNic(AntiAffinityNetworkInfoType.Nic value) {
        this.nic = value;
    }

    /**
     * Gets the value of the networkInfo property.
     * 
     * @return
     *     possible object is
     *     {@link AntiAffinityNetworkInfoType.NetworkInfo }
     *     
     */
    public AntiAffinityNetworkInfoType.NetworkInfo getNetworkInfo() {
        return networkInfo;
    }

    /**
     * Sets the value of the networkInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link AntiAffinityNetworkInfoType.NetworkInfo }
     *     
     */
    public void setNetworkInfo(AntiAffinityNetworkInfoType.NetworkInfo value) {
        this.networkInfo = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="primaryNic" type="{urn:didata.com:api:cloud:types}NicType"/&gt;
     *         &lt;element name="additionalNic" type="{urn:didata.com:api:cloud:types}NicType" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *       &lt;attribute name="networkDomainId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="networkDomainName" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "primaryNic",
        "additionalNic"
    })
    public static class NetworkInfo {

        @XmlElement(required = true)
        protected NicType primaryNic;
        protected List<NicType> additionalNic;
        @XmlAttribute(name = "networkDomainId", required = true)
        protected String networkDomainId;
        @XmlAttribute(name = "networkDomainName")
        protected String networkDomainName;

        /**
         * Gets the value of the primaryNic property.
         * 
         * @return
         *     possible object is
         *     {@link NicType }
         *     
         */
        public NicType getPrimaryNic() {
            return primaryNic;
        }

        /**
         * Sets the value of the primaryNic property.
         * 
         * @param value
         *     allowed object is
         *     {@link NicType }
         *     
         */
        public void setPrimaryNic(NicType value) {
            this.primaryNic = value;
        }

        /**
         * Gets the value of the additionalNic property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the additionalNic property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAdditionalNic().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link NicType }
         * 
         * 
         */
        public List<NicType> getAdditionalNic() {
            if (additionalNic == null) {
                additionalNic = new ArrayList<NicType>();
            }
            return this.additionalNic;
        }

        /**
         * Gets the value of the networkDomainId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNetworkDomainId() {
            return networkDomainId;
        }

        /**
         * Sets the value of the networkDomainId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNetworkDomainId(String value) {
            this.networkDomainId = value;
        }

        /**
         * Gets the value of the networkDomainName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNetworkDomainName() {
            return networkDomainName;
        }

        /**
         * Sets the value of the networkDomainName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNetworkDomainName(String value) {
            this.networkDomainName = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="privateIpv4" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="networkId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="networkName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="macAddress" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="state" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Nic {

        @XmlAttribute(name = "id", required = true)
        protected String id;
        @XmlAttribute(name = "privateIpv4", required = true)
        protected String privateIpv4;
        @XmlAttribute(name = "networkId", required = true)
        protected String networkId;
        @XmlAttribute(name = "networkName", required = true)
        protected String networkName;
        @XmlAttribute(name = "macAddress")
        protected String macAddress;
        @XmlAttribute(name = "state", required = true)
        protected String state;

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the privateIpv4 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrivateIpv4() {
            return privateIpv4;
        }

        /**
         * Sets the value of the privateIpv4 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrivateIpv4(String value) {
            this.privateIpv4 = value;
        }

        /**
         * Gets the value of the networkId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNetworkId() {
            return networkId;
        }

        /**
         * Sets the value of the networkId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNetworkId(String value) {
            this.networkId = value;
        }

        /**
         * Gets the value of the networkName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNetworkName() {
            return networkName;
        }

        /**
         * Sets the value of the networkName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNetworkName(String value) {
            this.networkName = value;
        }

        /**
         * Gets the value of the macAddress property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMacAddress() {
            return macAddress;
        }

        /**
         * Sets the value of the macAddress property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMacAddress(String value) {
            this.macAddress = value;
        }

        /**
         * Gets the value of the state property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getState() {
            return state;
        }

        /**
         * Sets the value of the state property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setState(String value) {
            this.state = value;
        }

    }

}
