//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.18 at 05:54:38 PM GMT 
//


package com.dimensiondata.cloud.client.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DatacenterType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DatacenterType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="displayName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="country" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="vpnUrl" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ftpsHost" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="networking" type="{urn:didata.com:api:cloud:types}NetworkingType"/&gt;
 *         &lt;element name="hypervisor" type="{urn:didata.com:api:cloud:types}HypervisorType"/&gt;
 *         &lt;element name="backup" type="{urn:didata.com:api:cloud:types}BackupType" minOccurs="0"/&gt;
 *         &lt;element name="consoleAccess" type="{urn:didata.com:api:cloud:types}ConsoleAccessType" minOccurs="0"/&gt;
 *         &lt;element name="monitoring" type="{urn:didata.com:api:cloud:types}MonitoringType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DatacenterType", propOrder = {
    "displayName",
    "city",
    "state",
    "country",
    "vpnUrl",
    "ftpsHost",
    "networking",
    "hypervisor",
    "backup",
    "consoleAccess",
    "monitoring"
})
public class DatacenterType {

    @XmlElement(required = true)
    protected String displayName;
    @XmlElement(required = true)
    protected String city;
    protected String state;
    @XmlElement(required = true)
    protected String country;
    @XmlElement(required = true)
    protected String vpnUrl;
    @XmlElement(required = true)
    protected String ftpsHost;
    @XmlElement(required = true)
    protected NetworkingType networking;
    @XmlElement(required = true)
    protected HypervisorType hypervisor;
    protected BackupType backup;
    protected ConsoleAccessType consoleAccess;
    protected MonitoringType monitoring;
    @XmlAttribute(name = "id", required = true)
    protected String id;
    @XmlAttribute(name = "type", required = true)
    protected String type;

    /**
     * Gets the value of the displayName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * Sets the value of the displayName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplayName(String value) {
        this.displayName = value;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCity(String value) {
        this.city = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountry(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the vpnUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVpnUrl() {
        return vpnUrl;
    }

    /**
     * Sets the value of the vpnUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVpnUrl(String value) {
        this.vpnUrl = value;
    }

    /**
     * Gets the value of the ftpsHost property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFtpsHost() {
        return ftpsHost;
    }

    /**
     * Sets the value of the ftpsHost property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFtpsHost(String value) {
        this.ftpsHost = value;
    }

    /**
     * Gets the value of the networking property.
     * 
     * @return
     *     possible object is
     *     {@link NetworkingType }
     *     
     */
    public NetworkingType getNetworking() {
        return networking;
    }

    /**
     * Sets the value of the networking property.
     * 
     * @param value
     *     allowed object is
     *     {@link NetworkingType }
     *     
     */
    public void setNetworking(NetworkingType value) {
        this.networking = value;
    }

    /**
     * Gets the value of the hypervisor property.
     * 
     * @return
     *     possible object is
     *     {@link HypervisorType }
     *     
     */
    public HypervisorType getHypervisor() {
        return hypervisor;
    }

    /**
     * Sets the value of the hypervisor property.
     * 
     * @param value
     *     allowed object is
     *     {@link HypervisorType }
     *     
     */
    public void setHypervisor(HypervisorType value) {
        this.hypervisor = value;
    }

    /**
     * Gets the value of the backup property.
     * 
     * @return
     *     possible object is
     *     {@link BackupType }
     *     
     */
    public BackupType getBackup() {
        return backup;
    }

    /**
     * Sets the value of the backup property.
     * 
     * @param value
     *     allowed object is
     *     {@link BackupType }
     *     
     */
    public void setBackup(BackupType value) {
        this.backup = value;
    }

    /**
     * Gets the value of the consoleAccess property.
     * 
     * @return
     *     possible object is
     *     {@link ConsoleAccessType }
     *     
     */
    public ConsoleAccessType getConsoleAccess() {
        return consoleAccess;
    }

    /**
     * Sets the value of the consoleAccess property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConsoleAccessType }
     *     
     */
    public void setConsoleAccess(ConsoleAccessType value) {
        this.consoleAccess = value;
    }

    /**
     * Gets the value of the monitoring property.
     * 
     * @return
     *     possible object is
     *     {@link MonitoringType }
     *     
     */
    public MonitoringType getMonitoring() {
        return monitoring;
    }

    /**
     * Sets the value of the monitoring property.
     * 
     * @param value
     *     allowed object is
     *     {@link MonitoringType }
     *     
     */
    public void setMonitoring(MonitoringType value) {
        this.monitoring = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

}
