//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.18 at 05:54:38 PM GMT 
//


package com.dimensiondata.cloud.client.model;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="connectionLimit" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/&gt;
 *         &lt;element name="connectionRateLimit" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/&gt;
 *         &lt;element name="sourcePortPreservation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="poolId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="clientClonePoolId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="persistenceProfileId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="fallbackPersistenceProfileId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="optimizationProfile" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;list itemType="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="iruleId" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "description",
    "enabled",
    "connectionLimit",
    "connectionRateLimit",
    "sourcePortPreservation",
    "poolId",
    "clientClonePoolId",
    "persistenceProfileId",
    "fallbackPersistenceProfileId",
    "optimizationProfile",
    "iruleId"
})
@XmlRootElement(name = "editVirtualListener")
public class EditVirtualListener {

    @XmlElementRef(name = "description", namespace = "urn:didata.com:api:cloud:types", type = JAXBElement.class, required = false)
    protected JAXBElement<String> description;
    protected Boolean enabled;
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger connectionLimit;
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger connectionRateLimit;
    protected String sourcePortPreservation;
    @XmlElementRef(name = "poolId", namespace = "urn:didata.com:api:cloud:types", type = JAXBElement.class, required = false)
    protected JAXBElement<String> poolId;
    @XmlElementRef(name = "clientClonePoolId", namespace = "urn:didata.com:api:cloud:types", type = JAXBElement.class, required = false)
    protected JAXBElement<String> clientClonePoolId;
    @XmlElementRef(name = "persistenceProfileId", namespace = "urn:didata.com:api:cloud:types", type = JAXBElement.class, required = false)
    protected JAXBElement<String> persistenceProfileId;
    @XmlElementRef(name = "fallbackPersistenceProfileId", namespace = "urn:didata.com:api:cloud:types", type = JAXBElement.class, required = false)
    protected JAXBElement<String> fallbackPersistenceProfileId;
    @XmlElementRef(name = "optimizationProfile", namespace = "urn:didata.com:api:cloud:types", type = JAXBElement.class, required = false)
    protected List<JAXBElement<List<String>>> optimizationProfile;
    @XmlElement(nillable = true)
    protected List<String> iruleId;
    @XmlAttribute(name = "id", required = true)
    protected String id;

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setDescription(JAXBElement<String> value) {
        this.description = value;
    }

    /**
     * Gets the value of the enabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEnabled() {
        return enabled;
    }

    /**
     * Sets the value of the enabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEnabled(Boolean value) {
        this.enabled = value;
    }

    /**
     * Gets the value of the connectionLimit property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getConnectionLimit() {
        return connectionLimit;
    }

    /**
     * Sets the value of the connectionLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setConnectionLimit(BigInteger value) {
        this.connectionLimit = value;
    }

    /**
     * Gets the value of the connectionRateLimit property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getConnectionRateLimit() {
        return connectionRateLimit;
    }

    /**
     * Sets the value of the connectionRateLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setConnectionRateLimit(BigInteger value) {
        this.connectionRateLimit = value;
    }

    /**
     * Gets the value of the sourcePortPreservation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourcePortPreservation() {
        return sourcePortPreservation;
    }

    /**
     * Sets the value of the sourcePortPreservation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourcePortPreservation(String value) {
        this.sourcePortPreservation = value;
    }

    /**
     * Gets the value of the poolId property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getPoolId() {
        return poolId;
    }

    /**
     * Sets the value of the poolId property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setPoolId(JAXBElement<String> value) {
        this.poolId = value;
    }

    /**
     * Gets the value of the clientClonePoolId property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getClientClonePoolId() {
        return clientClonePoolId;
    }

    /**
     * Sets the value of the clientClonePoolId property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setClientClonePoolId(JAXBElement<String> value) {
        this.clientClonePoolId = value;
    }

    /**
     * Gets the value of the persistenceProfileId property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getPersistenceProfileId() {
        return persistenceProfileId;
    }

    /**
     * Sets the value of the persistenceProfileId property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setPersistenceProfileId(JAXBElement<String> value) {
        this.persistenceProfileId = value;
    }

    /**
     * Gets the value of the fallbackPersistenceProfileId property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getFallbackPersistenceProfileId() {
        return fallbackPersistenceProfileId;
    }

    /**
     * Sets the value of the fallbackPersistenceProfileId property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setFallbackPersistenceProfileId(JAXBElement<String> value) {
        this.fallbackPersistenceProfileId = value;
    }

    /**
     * Gets the value of the optimizationProfile property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the optimizationProfile property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOptimizationProfile().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link List }{@code <}{@link String }{@code >}{@code >}
     * 
     * 
     */
    public List<JAXBElement<List<String>>> getOptimizationProfile() {
        if (optimizationProfile == null) {
            optimizationProfile = new ArrayList<JAXBElement<List<String>>>();
        }
        return this.optimizationProfile;
    }

    /**
     * Gets the value of the iruleId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the iruleId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIruleId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getIruleId() {
        if (iruleId == null) {
            iruleId = new ArrayList<String>();
        }
        return this.iruleId;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
