//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.18 at 05:54:38 PM GMT 
//


package com.dimensiondata.cloud.client.model;

import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.dimensiondata.cloud.client.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Response_QNAME = new QName("urn:didata.com:api:cloud:types", "response");
    private final static QName _Server_QNAME = new QName("urn:didata.com:api:cloud:types", "server");
    private final static QName _DeployServer_QNAME = new QName("urn:didata.com:api:cloud:types", "deployServer");
    private final static QName _NotifyNicIpChange_QNAME = new QName("urn:didata.com:api:cloud:types", "notifyNicIpChange");
    private final static QName _StartServer_QNAME = new QName("urn:didata.com:api:cloud:types", "startServer");
    private final static QName _ShutdownServer_QNAME = new QName("urn:didata.com:api:cloud:types", "shutdownServer");
    private final static QName _PowerOffServer_QNAME = new QName("urn:didata.com:api:cloud:types", "powerOffServer");
    private final static QName _RebootServer_QNAME = new QName("urn:didata.com:api:cloud:types", "rebootServer");
    private final static QName _ResetServer_QNAME = new QName("urn:didata.com:api:cloud:types", "resetServer");
    private final static QName _DeleteServer_QNAME = new QName("urn:didata.com:api:cloud:types", "deleteServer");
    private final static QName _CleanServer_QNAME = new QName("urn:didata.com:api:cloud:types", "cleanServer");
    private final static QName _UpdateVmwareTools_QNAME = new QName("urn:didata.com:api:cloud:types", "updateVmwareTools");
    private final static QName _RemoveNic_QNAME = new QName("urn:didata.com:api:cloud:types", "removeNic");
    private final static QName _AddNic_QNAME = new QName("urn:didata.com:api:cloud:types", "addNic");
    private final static QName _EnableServerMonitoring_QNAME = new QName("urn:didata.com:api:cloud:types", "enableServerMonitoring");
    private final static QName _DisableServerMonitoring_QNAME = new QName("urn:didata.com:api:cloud:types", "disableServerMonitoring");
    private final static QName _ChangeServerMonitoringPlan_QNAME = new QName("urn:didata.com:api:cloud:types", "changeServerMonitoringPlan");
    private final static QName _AddLocalDisk_QNAME = new QName("urn:didata.com:api:cloud:types", "addLocalDisk");
    private final static QName _FirewallRule_QNAME = new QName("urn:didata.com:api:cloud:types", "firewallRule");
    private final static QName _CreateFirewallRule_QNAME = new QName("urn:didata.com:api:cloud:types", "createFirewallRule");
    private final static QName _DeleteFirewallRule_QNAME = new QName("urn:didata.com:api:cloud:types", "deleteFirewallRule");
    private final static QName _EditFirewallRule_QNAME = new QName("urn:didata.com:api:cloud:types", "editFirewallRule");
    private final static QName _DefaultHealthMonitor_QNAME = new QName("urn:didata.com:api:cloud:types", "defaultHealthMonitor");
    private final static QName _VirtualListener_QNAME = new QName("urn:didata.com:api:cloud:types", "virtualListener");
    private final static QName _DeleteVirtualListener_QNAME = new QName("urn:didata.com:api:cloud:types", "deleteVirtualListener");
    private final static QName _NatRule_QNAME = new QName("urn:didata.com:api:cloud:types", "natRule");
    private final static QName _DeleteNatRule_QNAME = new QName("urn:didata.com:api:cloud:types", "deleteNatRule");
    private final static QName _NetworkDomain_QNAME = new QName("urn:didata.com:api:cloud:types", "networkDomain");
    private final static QName _DeployNetworkDomain_QNAME = new QName("urn:didata.com:api:cloud:types", "deployNetworkDomain");
    private final static QName _EditNetworkDomain_QNAME = new QName("urn:didata.com:api:cloud:types", "editNetworkDomain");
    private final static QName _DeleteNetworkDomain_QNAME = new QName("urn:didata.com:api:cloud:types", "deleteNetworkDomain");
    private final static QName _Node_QNAME = new QName("urn:didata.com:api:cloud:types", "node");
    private final static QName _CreateNode_QNAME = new QName("urn:didata.com:api:cloud:types", "createNode");
    private final static QName _DeleteNode_QNAME = new QName("urn:didata.com:api:cloud:types", "deleteNode");
    private final static QName _DefaultPersistenceProfile_QNAME = new QName("urn:didata.com:api:cloud:types", "defaultPersistenceProfile");
    private final static QName _Pool_QNAME = new QName("urn:didata.com:api:cloud:types", "pool");
    private final static QName _DeletePool_QNAME = new QName("urn:didata.com:api:cloud:types", "deletePool");
    private final static QName _PoolMember_QNAME = new QName("urn:didata.com:api:cloud:types", "poolMember");
    private final static QName _RemovePoolMember_QNAME = new QName("urn:didata.com:api:cloud:types", "removePoolMember");
    private final static QName _PublicIpBlock_QNAME = new QName("urn:didata.com:api:cloud:types", "publicIpBlock");
    private final static QName _AddPublicIpBlock_QNAME = new QName("urn:didata.com:api:cloud:types", "addPublicIpBlock");
    private final static QName _RemovePublicIpBlock_QNAME = new QName("urn:didata.com:api:cloud:types", "removePublicIpBlock");
    private final static QName _Vlan_QNAME = new QName("urn:didata.com:api:cloud:types", "vlan");
    private final static QName _DeployVlan_QNAME = new QName("urn:didata.com:api:cloud:types", "deployVlan");
    private final static QName _EditVlan_QNAME = new QName("urn:didata.com:api:cloud:types", "editVlan");
    private final static QName _DeleteVlan_QNAME = new QName("urn:didata.com:api:cloud:types", "deleteVlan");
    private final static QName _ExpandVlan_QNAME = new QName("urn:didata.com:api:cloud:types", "expandVlan");
    private final static QName _EditVirtualListenerDescription_QNAME = new QName("urn:didata.com:api:cloud:types", "description");
    private final static QName _EditVirtualListenerPoolId_QNAME = new QName("urn:didata.com:api:cloud:types", "poolId");
    private final static QName _EditVirtualListenerClientClonePoolId_QNAME = new QName("urn:didata.com:api:cloud:types", "clientClonePoolId");
    private final static QName _EditVirtualListenerPersistenceProfileId_QNAME = new QName("urn:didata.com:api:cloud:types", "persistenceProfileId");
    private final static QName _EditVirtualListenerFallbackPersistenceProfileId_QNAME = new QName("urn:didata.com:api:cloud:types", "fallbackPersistenceProfileId");
    private final static QName _EditVirtualListenerOptimizationProfile_QNAME = new QName("urn:didata.com:api:cloud:types", "optimizationProfile");
    private final static QName _EditNodeHealthMonitorId_QNAME = new QName("urn:didata.com:api:cloud:types", "healthMonitorId");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.dimensiondata.cloud.client.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link IpAndPortFilterType }
     * 
     */
    public IpAndPortFilterType createIpAndPortFilterType() {
        return new IpAndPortFilterType();
    }

    /**
     * Create an instance of {@link AntiAffinityNetworkInfoType }
     * 
     */
    public AntiAffinityNetworkInfoType createAntiAffinityNetworkInfoType() {
        return new AntiAffinityNetworkInfoType();
    }

    /**
     * Create an instance of {@link VlanType }
     * 
     */
    public VlanType createVlanType() {
        return new VlanType();
    }

    /**
     * Create an instance of {@link PoolMemberType }
     * 
     */
    public PoolMemberType createPoolMemberType() {
        return new PoolMemberType();
    }

    /**
     * Create an instance of {@link NodeType }
     * 
     */
    public NodeType createNodeType() {
        return new NodeType();
    }

    /**
     * Create an instance of {@link AntiAffinityRuleType }
     * 
     */
    public AntiAffinityRuleType createAntiAffinityRuleType() {
        return new AntiAffinityRuleType();
    }

    /**
     * Create an instance of {@link DeployServerType }
     * 
     */
    public DeployServerType createDeployServerType() {
        return new DeployServerType();
    }

    /**
     * Create an instance of {@link ServerType }
     * 
     */
    public ServerType createServerType() {
        return new ServerType();
    }

    /**
     * Create an instance of {@link ResponseType }
     * 
     */
    public ResponseType createResponseType() {
        return new ResponseType();
    }

    /**
     * Create an instance of {@link Servers }
     * 
     */
    public Servers createServers() {
        return new Servers();
    }

    /**
     * Create an instance of {@link NotifyNicIpChangeType }
     * 
     */
    public NotifyNicIpChangeType createNotifyNicIpChangeType() {
        return new NotifyNicIpChangeType();
    }

    /**
     * Create an instance of {@link IdType }
     * 
     */
    public IdType createIdType() {
        return new IdType();
    }

    /**
     * Create an instance of {@link AddNicType }
     * 
     */
    public AddNicType createAddNicType() {
        return new AddNicType();
    }

    /**
     * Create an instance of {@link EnableServerMonitoringType }
     * 
     */
    public EnableServerMonitoringType createEnableServerMonitoringType() {
        return new EnableServerMonitoringType();
    }

    /**
     * Create an instance of {@link ChangeServerMonitoringPlanType }
     * 
     */
    public ChangeServerMonitoringPlanType createChangeServerMonitoringPlanType() {
        return new ChangeServerMonitoringPlanType();
    }

    /**
     * Create an instance of {@link AddLocalDiskType }
     * 
     */
    public AddLocalDiskType createAddLocalDiskType() {
        return new AddLocalDiskType();
    }

    /**
     * Create an instance of {@link AntiAffinityRules }
     * 
     */
    public AntiAffinityRules createAntiAffinityRules() {
        return new AntiAffinityRules();
    }

    /**
     * Create an instance of {@link Datacenters }
     * 
     */
    public Datacenters createDatacenters() {
        return new Datacenters();
    }

    /**
     * Create an instance of {@link DatacenterType }
     * 
     */
    public DatacenterType createDatacenterType() {
        return new DatacenterType();
    }

    /**
     * Create an instance of {@link FirewallRuleType }
     * 
     */
    public FirewallRuleType createFirewallRuleType() {
        return new FirewallRuleType();
    }

    /**
     * Create an instance of {@link FirewallRules }
     * 
     */
    public FirewallRules createFirewallRules() {
        return new FirewallRules();
    }

    /**
     * Create an instance of {@link CreateFirewallRuleType }
     * 
     */
    public CreateFirewallRuleType createCreateFirewallRuleType() {
        return new CreateFirewallRuleType();
    }

    /**
     * Create an instance of {@link EditFirewallRuleType }
     * 
     */
    public EditFirewallRuleType createEditFirewallRuleType() {
        return new EditFirewallRuleType();
    }

    /**
     * Create an instance of {@link DefaultHealthMonitorType }
     * 
     */
    public DefaultHealthMonitorType createDefaultHealthMonitorType() {
        return new DefaultHealthMonitorType();
    }

    /**
     * Create an instance of {@link DefaultHealthMonitors }
     * 
     */
    public DefaultHealthMonitors createDefaultHealthMonitors() {
        return new DefaultHealthMonitors();
    }

    /**
     * Create an instance of {@link ReservedPrivateIpv4Addresses }
     * 
     */
    public ReservedPrivateIpv4Addresses createReservedPrivateIpv4Addresses() {
        return new ReservedPrivateIpv4Addresses();
    }

    /**
     * Create an instance of {@link ReservedPrivateIpv4AddressType }
     * 
     */
    public ReservedPrivateIpv4AddressType createReservedPrivateIpv4AddressType() {
        return new ReservedPrivateIpv4AddressType();
    }

    /**
     * Create an instance of {@link ReservedPublicIpv4Addresses }
     * 
     */
    public ReservedPublicIpv4Addresses createReservedPublicIpv4Addresses() {
        return new ReservedPublicIpv4Addresses();
    }

    /**
     * Create an instance of {@link ReservedPublicIpv4AddressType }
     * 
     */
    public ReservedPublicIpv4AddressType createReservedPublicIpv4AddressType() {
        return new ReservedPublicIpv4AddressType();
    }

    /**
     * Create an instance of {@link CreateVirtualListener }
     * 
     */
    public CreateVirtualListener createCreateVirtualListener() {
        return new CreateVirtualListener();
    }

    /**
     * Create an instance of {@link EditVirtualListener }
     * 
     */
    public EditVirtualListener createEditVirtualListener() {
        return new EditVirtualListener();
    }

    /**
     * Create an instance of {@link VirtualListeners }
     * 
     */
    public VirtualListeners createVirtualListeners() {
        return new VirtualListeners();
    }

    /**
     * Create an instance of {@link VirtualListenerType }
     * 
     */
    public VirtualListenerType createVirtualListenerType() {
        return new VirtualListenerType();
    }

    /**
     * Create an instance of {@link DefaultIrules }
     * 
     */
    public DefaultIrules createDefaultIrules() {
        return new DefaultIrules();
    }

    /**
     * Create an instance of {@link DefaultIruleType }
     * 
     */
    public DefaultIruleType createDefaultIruleType() {
        return new DefaultIruleType();
    }

    /**
     * Create an instance of {@link NatRules }
     * 
     */
    public NatRules createNatRules() {
        return new NatRules();
    }

    /**
     * Create an instance of {@link NatRuleType }
     * 
     */
    public NatRuleType createNatRuleType() {
        return new NatRuleType();
    }

    /**
     * Create an instance of {@link CreateNatRule }
     * 
     */
    public CreateNatRule createCreateNatRule() {
        return new CreateNatRule();
    }

    /**
     * Create an instance of {@link NetworkDomainType }
     * 
     */
    public NetworkDomainType createNetworkDomainType() {
        return new NetworkDomainType();
    }

    /**
     * Create an instance of {@link NetworkDomains }
     * 
     */
    public NetworkDomains createNetworkDomains() {
        return new NetworkDomains();
    }

    /**
     * Create an instance of {@link DeployNetworkDomainType }
     * 
     */
    public DeployNetworkDomainType createDeployNetworkDomainType() {
        return new DeployNetworkDomainType();
    }

    /**
     * Create an instance of {@link EditNetworkDomainType }
     * 
     */
    public EditNetworkDomainType createEditNetworkDomainType() {
        return new EditNetworkDomainType();
    }

    /**
     * Create an instance of {@link Nodes }
     * 
     */
    public Nodes createNodes() {
        return new Nodes();
    }

    /**
     * Create an instance of {@link CreateNodeType }
     * 
     */
    public CreateNodeType createCreateNodeType() {
        return new CreateNodeType();
    }

    /**
     * Create an instance of {@link EditNode }
     * 
     */
    public EditNode createEditNode() {
        return new EditNode();
    }

    /**
     * Create an instance of {@link DefaultPersistenceProfileType }
     * 
     */
    public DefaultPersistenceProfileType createDefaultPersistenceProfileType() {
        return new DefaultPersistenceProfileType();
    }

    /**
     * Create an instance of {@link DefaultPersistenceProfiles }
     * 
     */
    public DefaultPersistenceProfiles createDefaultPersistenceProfiles() {
        return new DefaultPersistenceProfiles();
    }

    /**
     * Create an instance of {@link PoolType }
     * 
     */
    public PoolType createPoolType() {
        return new PoolType();
    }

    /**
     * Create an instance of {@link Pools }
     * 
     */
    public Pools createPools() {
        return new Pools();
    }

    /**
     * Create an instance of {@link CreatePool }
     * 
     */
    public CreatePool createCreatePool() {
        return new CreatePool();
    }

    /**
     * Create an instance of {@link EditPool }
     * 
     */
    public EditPool createEditPool() {
        return new EditPool();
    }

    /**
     * Create an instance of {@link PoolMembers }
     * 
     */
    public PoolMembers createPoolMembers() {
        return new PoolMembers();
    }

    /**
     * Create an instance of {@link AddPoolMember }
     * 
     */
    public AddPoolMember createAddPoolMember() {
        return new AddPoolMember();
    }

    /**
     * Create an instance of {@link EditPoolMember }
     * 
     */
    public EditPoolMember createEditPoolMember() {
        return new EditPoolMember();
    }

    /**
     * Create an instance of {@link PublicIpBlockType }
     * 
     */
    public PublicIpBlockType createPublicIpBlockType() {
        return new PublicIpBlockType();
    }

    /**
     * Create an instance of {@link PublicIpBlocks }
     * 
     */
    public PublicIpBlocks createPublicIpBlocks() {
        return new PublicIpBlocks();
    }

    /**
     * Create an instance of {@link AddPublicIpBlockType }
     * 
     */
    public AddPublicIpBlockType createAddPublicIpBlockType() {
        return new AddPublicIpBlockType();
    }

    /**
     * Create an instance of {@link Vlans }
     * 
     */
    public Vlans createVlans() {
        return new Vlans();
    }

    /**
     * Create an instance of {@link DeployVlanType }
     * 
     */
    public DeployVlanType createDeployVlanType() {
        return new DeployVlanType();
    }

    /**
     * Create an instance of {@link EditVlanType }
     * 
     */
    public EditVlanType createEditVlanType() {
        return new EditVlanType();
    }

    /**
     * Create an instance of {@link ExpandVlanType }
     * 
     */
    public ExpandVlanType createExpandVlanType() {
        return new ExpandVlanType();
    }

    /**
     * Create an instance of {@link NameValuePairType }
     * 
     */
    public NameValuePairType createNameValuePairType() {
        return new NameValuePairType();
    }

    /**
     * Create an instance of {@link ProgressType }
     * 
     */
    public ProgressType createProgressType() {
        return new ProgressType();
    }

    /**
     * Create an instance of {@link ProgressStepType }
     * 
     */
    public ProgressStepType createProgressStepType() {
        return new ProgressStepType();
    }

    /**
     * Create an instance of {@link IpRangeCidrType }
     * 
     */
    public IpRangeCidrType createIpRangeCidrType() {
        return new IpRangeCidrType();
    }

    /**
     * Create an instance of {@link OperatingSystemType }
     * 
     */
    public OperatingSystemType createOperatingSystemType() {
        return new OperatingSystemType();
    }

    /**
     * Create an instance of {@link PropertyType }
     * 
     */
    public PropertyType createPropertyType() {
        return new PropertyType();
    }

    /**
     * Create an instance of {@link IdAndNameType }
     * 
     */
    public IdAndNameType createIdAndNameType() {
        return new IdAndNameType();
    }

    /**
     * Create an instance of {@link NicType }
     * 
     */
    public NicType createNicType() {
        return new NicType();
    }

    /**
     * Create an instance of {@link VlanIdOrPrivateIpType }
     * 
     */
    public VlanIdOrPrivateIpType createVlanIdOrPrivateIpType() {
        return new VlanIdOrPrivateIpType();
    }

    /**
     * Create an instance of {@link NetworkingType }
     * 
     */
    public NetworkingType createNetworkingType() {
        return new NetworkingType();
    }

    /**
     * Create an instance of {@link HypervisorType }
     * 
     */
    public HypervisorType createHypervisorType() {
        return new HypervisorType();
    }

    /**
     * Create an instance of {@link DiskSpeedType }
     * 
     */
    public DiskSpeedType createDiskSpeedType() {
        return new DiskSpeedType();
    }

    /**
     * Create an instance of {@link BackupType }
     * 
     */
    public BackupType createBackupType() {
        return new BackupType();
    }

    /**
     * Create an instance of {@link ConsoleAccessType }
     * 
     */
    public ConsoleAccessType createConsoleAccessType() {
        return new ConsoleAccessType();
    }

    /**
     * Create an instance of {@link MonitoringType }
     * 
     */
    public MonitoringType createMonitoringType() {
        return new MonitoringType();
    }

    /**
     * Create an instance of {@link IcmpPropertiesType }
     * 
     */
    public IcmpPropertiesType createIcmpPropertiesType() {
        return new IcmpPropertiesType();
    }

    /**
     * Create an instance of {@link RulePlacementType }
     * 
     */
    public RulePlacementType createRulePlacementType() {
        return new RulePlacementType();
    }

    /**
     * Create an instance of {@link PoolSummaryType }
     * 
     */
    public PoolSummaryType createPoolSummaryType() {
        return new PoolSummaryType();
    }

    /**
     * Create an instance of {@link VirtualListenerCompatibilityType }
     * 
     */
    public VirtualListenerCompatibilityType createVirtualListenerCompatibilityType() {
        return new VirtualListenerCompatibilityType();
    }

    /**
     * Create an instance of {@link IpAndPortFilterType.Ip }
     * 
     */
    public IpAndPortFilterType.Ip createIpAndPortFilterTypeIp() {
        return new IpAndPortFilterType.Ip();
    }

    /**
     * Create an instance of {@link IpAndPortFilterType.Port }
     * 
     */
    public IpAndPortFilterType.Port createIpAndPortFilterTypePort() {
        return new IpAndPortFilterType.Port();
    }

    /**
     * Create an instance of {@link AntiAffinityNetworkInfoType.Nic }
     * 
     */
    public AntiAffinityNetworkInfoType.Nic createAntiAffinityNetworkInfoTypeNic() {
        return new AntiAffinityNetworkInfoType.Nic();
    }

    /**
     * Create an instance of {@link AntiAffinityNetworkInfoType.NetworkInfo }
     * 
     */
    public AntiAffinityNetworkInfoType.NetworkInfo createAntiAffinityNetworkInfoTypeNetworkInfo() {
        return new AntiAffinityNetworkInfoType.NetworkInfo();
    }

    /**
     * Create an instance of {@link VlanType.NetworkDomain }
     * 
     */
    public VlanType.NetworkDomain createVlanTypeNetworkDomain() {
        return new VlanType.NetworkDomain();
    }

    /**
     * Create an instance of {@link PoolMemberType.Node }
     * 
     */
    public PoolMemberType.Node createPoolMemberTypeNode() {
        return new PoolMemberType.Node();
    }

    /**
     * Create an instance of {@link NodeType.HealthMonitor }
     * 
     */
    public NodeType.HealthMonitor createNodeTypeHealthMonitor() {
        return new NodeType.HealthMonitor();
    }

    /**
     * Create an instance of {@link AntiAffinityRuleType.ServerSummary }
     * 
     */
    public AntiAffinityRuleType.ServerSummary createAntiAffinityRuleTypeServerSummary() {
        return new AntiAffinityRuleType.ServerSummary();
    }

    /**
     * Create an instance of {@link DeployServerType.Network }
     * 
     */
    public DeployServerType.Network createDeployServerTypeNetwork() {
        return new DeployServerType.Network();
    }

    /**
     * Create an instance of {@link DeployServerType.NetworkInfo }
     * 
     */
    public DeployServerType.NetworkInfo createDeployServerTypeNetworkInfo() {
        return new DeployServerType.NetworkInfo();
    }

    /**
     * Create an instance of {@link DeployServerType.Disk }
     * 
     */
    public DeployServerType.Disk createDeployServerTypeDisk() {
        return new DeployServerType.Disk();
    }

    /**
     * Create an instance of {@link ServerType.Disk }
     * 
     */
    public ServerType.Disk createServerTypeDisk() {
        return new ServerType.Disk();
    }

    /**
     * Create an instance of {@link ServerType.Nic }
     * 
     */
    public ServerType.Nic createServerTypeNic() {
        return new ServerType.Nic();
    }

    /**
     * Create an instance of {@link ServerType.NetworkInfo }
     * 
     */
    public ServerType.NetworkInfo createServerTypeNetworkInfo() {
        return new ServerType.NetworkInfo();
    }

    /**
     * Create an instance of {@link ServerType.Backup }
     * 
     */
    public ServerType.Backup createServerTypeBackup() {
        return new ServerType.Backup();
    }

    /**
     * Create an instance of {@link ServerType.Monitoring }
     * 
     */
    public ServerType.Monitoring createServerTypeMonitoring() {
        return new ServerType.Monitoring();
    }

    /**
     * Create an instance of {@link ServerType.MachineStatus }
     * 
     */
    public ServerType.MachineStatus createServerTypeMachineStatus() {
        return new ServerType.MachineStatus();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:didata.com:api:cloud:types", name = "response")
    public JAXBElement<ResponseType> createResponse(ResponseType value) {
        return new JAXBElement<ResponseType>(_Response_QNAME, ResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServerType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:didata.com:api:cloud:types", name = "server")
    public JAXBElement<ServerType> createServer(ServerType value) {
        return new JAXBElement<ServerType>(_Server_QNAME, ServerType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeployServerType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:didata.com:api:cloud:types", name = "deployServer")
    public JAXBElement<DeployServerType> createDeployServer(DeployServerType value) {
        return new JAXBElement<DeployServerType>(_DeployServer_QNAME, DeployServerType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NotifyNicIpChangeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:didata.com:api:cloud:types", name = "notifyNicIpChange")
    public JAXBElement<NotifyNicIpChangeType> createNotifyNicIpChange(NotifyNicIpChangeType value) {
        return new JAXBElement<NotifyNicIpChangeType>(_NotifyNicIpChange_QNAME, NotifyNicIpChangeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:didata.com:api:cloud:types", name = "startServer")
    public JAXBElement<IdType> createStartServer(IdType value) {
        return new JAXBElement<IdType>(_StartServer_QNAME, IdType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:didata.com:api:cloud:types", name = "shutdownServer")
    public JAXBElement<IdType> createShutdownServer(IdType value) {
        return new JAXBElement<IdType>(_ShutdownServer_QNAME, IdType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:didata.com:api:cloud:types", name = "powerOffServer")
    public JAXBElement<IdType> createPowerOffServer(IdType value) {
        return new JAXBElement<IdType>(_PowerOffServer_QNAME, IdType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:didata.com:api:cloud:types", name = "rebootServer")
    public JAXBElement<IdType> createRebootServer(IdType value) {
        return new JAXBElement<IdType>(_RebootServer_QNAME, IdType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:didata.com:api:cloud:types", name = "resetServer")
    public JAXBElement<IdType> createResetServer(IdType value) {
        return new JAXBElement<IdType>(_ResetServer_QNAME, IdType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:didata.com:api:cloud:types", name = "deleteServer")
    public JAXBElement<IdType> createDeleteServer(IdType value) {
        return new JAXBElement<IdType>(_DeleteServer_QNAME, IdType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:didata.com:api:cloud:types", name = "cleanServer")
    public JAXBElement<IdType> createCleanServer(IdType value) {
        return new JAXBElement<IdType>(_CleanServer_QNAME, IdType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:didata.com:api:cloud:types", name = "updateVmwareTools")
    public JAXBElement<IdType> createUpdateVmwareTools(IdType value) {
        return new JAXBElement<IdType>(_UpdateVmwareTools_QNAME, IdType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:didata.com:api:cloud:types", name = "removeNic")
    public JAXBElement<IdType> createRemoveNic(IdType value) {
        return new JAXBElement<IdType>(_RemoveNic_QNAME, IdType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddNicType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:didata.com:api:cloud:types", name = "addNic")
    public JAXBElement<AddNicType> createAddNic(AddNicType value) {
        return new JAXBElement<AddNicType>(_AddNic_QNAME, AddNicType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EnableServerMonitoringType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:didata.com:api:cloud:types", name = "enableServerMonitoring")
    public JAXBElement<EnableServerMonitoringType> createEnableServerMonitoring(EnableServerMonitoringType value) {
        return new JAXBElement<EnableServerMonitoringType>(_EnableServerMonitoring_QNAME, EnableServerMonitoringType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:didata.com:api:cloud:types", name = "disableServerMonitoring")
    public JAXBElement<IdType> createDisableServerMonitoring(IdType value) {
        return new JAXBElement<IdType>(_DisableServerMonitoring_QNAME, IdType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ChangeServerMonitoringPlanType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:didata.com:api:cloud:types", name = "changeServerMonitoringPlan")
    public JAXBElement<ChangeServerMonitoringPlanType> createChangeServerMonitoringPlan(ChangeServerMonitoringPlanType value) {
        return new JAXBElement<ChangeServerMonitoringPlanType>(_ChangeServerMonitoringPlan_QNAME, ChangeServerMonitoringPlanType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddLocalDiskType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:didata.com:api:cloud:types", name = "addLocalDisk")
    public JAXBElement<AddLocalDiskType> createAddLocalDisk(AddLocalDiskType value) {
        return new JAXBElement<AddLocalDiskType>(_AddLocalDisk_QNAME, AddLocalDiskType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FirewallRuleType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:didata.com:api:cloud:types", name = "firewallRule")
    public JAXBElement<FirewallRuleType> createFirewallRule(FirewallRuleType value) {
        return new JAXBElement<FirewallRuleType>(_FirewallRule_QNAME, FirewallRuleType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateFirewallRuleType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:didata.com:api:cloud:types", name = "createFirewallRule")
    public JAXBElement<CreateFirewallRuleType> createCreateFirewallRule(CreateFirewallRuleType value) {
        return new JAXBElement<CreateFirewallRuleType>(_CreateFirewallRule_QNAME, CreateFirewallRuleType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:didata.com:api:cloud:types", name = "deleteFirewallRule")
    public JAXBElement<IdType> createDeleteFirewallRule(IdType value) {
        return new JAXBElement<IdType>(_DeleteFirewallRule_QNAME, IdType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EditFirewallRuleType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:didata.com:api:cloud:types", name = "editFirewallRule")
    public JAXBElement<EditFirewallRuleType> createEditFirewallRule(EditFirewallRuleType value) {
        return new JAXBElement<EditFirewallRuleType>(_EditFirewallRule_QNAME, EditFirewallRuleType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DefaultHealthMonitorType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:didata.com:api:cloud:types", name = "defaultHealthMonitor")
    public JAXBElement<DefaultHealthMonitorType> createDefaultHealthMonitor(DefaultHealthMonitorType value) {
        return new JAXBElement<DefaultHealthMonitorType>(_DefaultHealthMonitor_QNAME, DefaultHealthMonitorType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VirtualListenerType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:didata.com:api:cloud:types", name = "virtualListener")
    public JAXBElement<VirtualListenerType> createVirtualListener(VirtualListenerType value) {
        return new JAXBElement<VirtualListenerType>(_VirtualListener_QNAME, VirtualListenerType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:didata.com:api:cloud:types", name = "deleteVirtualListener")
    public JAXBElement<IdType> createDeleteVirtualListener(IdType value) {
        return new JAXBElement<IdType>(_DeleteVirtualListener_QNAME, IdType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NatRuleType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:didata.com:api:cloud:types", name = "natRule")
    public JAXBElement<NatRuleType> createNatRule(NatRuleType value) {
        return new JAXBElement<NatRuleType>(_NatRule_QNAME, NatRuleType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:didata.com:api:cloud:types", name = "deleteNatRule")
    public JAXBElement<IdType> createDeleteNatRule(IdType value) {
        return new JAXBElement<IdType>(_DeleteNatRule_QNAME, IdType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NetworkDomainType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:didata.com:api:cloud:types", name = "networkDomain")
    public JAXBElement<NetworkDomainType> createNetworkDomain(NetworkDomainType value) {
        return new JAXBElement<NetworkDomainType>(_NetworkDomain_QNAME, NetworkDomainType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeployNetworkDomainType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:didata.com:api:cloud:types", name = "deployNetworkDomain")
    public JAXBElement<DeployNetworkDomainType> createDeployNetworkDomain(DeployNetworkDomainType value) {
        return new JAXBElement<DeployNetworkDomainType>(_DeployNetworkDomain_QNAME, DeployNetworkDomainType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EditNetworkDomainType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:didata.com:api:cloud:types", name = "editNetworkDomain")
    public JAXBElement<EditNetworkDomainType> createEditNetworkDomain(EditNetworkDomainType value) {
        return new JAXBElement<EditNetworkDomainType>(_EditNetworkDomain_QNAME, EditNetworkDomainType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:didata.com:api:cloud:types", name = "deleteNetworkDomain")
    public JAXBElement<IdType> createDeleteNetworkDomain(IdType value) {
        return new JAXBElement<IdType>(_DeleteNetworkDomain_QNAME, IdType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NodeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:didata.com:api:cloud:types", name = "node")
    public JAXBElement<NodeType> createNode(NodeType value) {
        return new JAXBElement<NodeType>(_Node_QNAME, NodeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateNodeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:didata.com:api:cloud:types", name = "createNode")
    public JAXBElement<CreateNodeType> createCreateNode(CreateNodeType value) {
        return new JAXBElement<CreateNodeType>(_CreateNode_QNAME, CreateNodeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:didata.com:api:cloud:types", name = "deleteNode")
    public JAXBElement<IdType> createDeleteNode(IdType value) {
        return new JAXBElement<IdType>(_DeleteNode_QNAME, IdType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DefaultPersistenceProfileType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:didata.com:api:cloud:types", name = "defaultPersistenceProfile")
    public JAXBElement<DefaultPersistenceProfileType> createDefaultPersistenceProfile(DefaultPersistenceProfileType value) {
        return new JAXBElement<DefaultPersistenceProfileType>(_DefaultPersistenceProfile_QNAME, DefaultPersistenceProfileType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PoolType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:didata.com:api:cloud:types", name = "pool")
    public JAXBElement<PoolType> createPool(PoolType value) {
        return new JAXBElement<PoolType>(_Pool_QNAME, PoolType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:didata.com:api:cloud:types", name = "deletePool")
    public JAXBElement<IdType> createDeletePool(IdType value) {
        return new JAXBElement<IdType>(_DeletePool_QNAME, IdType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PoolMemberType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:didata.com:api:cloud:types", name = "poolMember")
    public JAXBElement<PoolMemberType> createPoolMember(PoolMemberType value) {
        return new JAXBElement<PoolMemberType>(_PoolMember_QNAME, PoolMemberType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:didata.com:api:cloud:types", name = "removePoolMember")
    public JAXBElement<IdType> createRemovePoolMember(IdType value) {
        return new JAXBElement<IdType>(_RemovePoolMember_QNAME, IdType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PublicIpBlockType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:didata.com:api:cloud:types", name = "publicIpBlock")
    public JAXBElement<PublicIpBlockType> createPublicIpBlock(PublicIpBlockType value) {
        return new JAXBElement<PublicIpBlockType>(_PublicIpBlock_QNAME, PublicIpBlockType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddPublicIpBlockType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:didata.com:api:cloud:types", name = "addPublicIpBlock")
    public JAXBElement<AddPublicIpBlockType> createAddPublicIpBlock(AddPublicIpBlockType value) {
        return new JAXBElement<AddPublicIpBlockType>(_AddPublicIpBlock_QNAME, AddPublicIpBlockType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:didata.com:api:cloud:types", name = "removePublicIpBlock")
    public JAXBElement<IdType> createRemovePublicIpBlock(IdType value) {
        return new JAXBElement<IdType>(_RemovePublicIpBlock_QNAME, IdType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VlanType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:didata.com:api:cloud:types", name = "vlan")
    public JAXBElement<VlanType> createVlan(VlanType value) {
        return new JAXBElement<VlanType>(_Vlan_QNAME, VlanType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeployVlanType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:didata.com:api:cloud:types", name = "deployVlan")
    public JAXBElement<DeployVlanType> createDeployVlan(DeployVlanType value) {
        return new JAXBElement<DeployVlanType>(_DeployVlan_QNAME, DeployVlanType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EditVlanType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:didata.com:api:cloud:types", name = "editVlan")
    public JAXBElement<EditVlanType> createEditVlan(EditVlanType value) {
        return new JAXBElement<EditVlanType>(_EditVlan_QNAME, EditVlanType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:didata.com:api:cloud:types", name = "deleteVlan")
    public JAXBElement<IdType> createDeleteVlan(IdType value) {
        return new JAXBElement<IdType>(_DeleteVlan_QNAME, IdType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExpandVlanType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:didata.com:api:cloud:types", name = "expandVlan")
    public JAXBElement<ExpandVlanType> createExpandVlan(ExpandVlanType value) {
        return new JAXBElement<ExpandVlanType>(_ExpandVlan_QNAME, ExpandVlanType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:didata.com:api:cloud:types", name = "description", scope = EditVirtualListener.class)
    public JAXBElement<String> createEditVirtualListenerDescription(String value) {
        return new JAXBElement<String>(_EditVirtualListenerDescription_QNAME, String.class, EditVirtualListener.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:didata.com:api:cloud:types", name = "poolId", scope = EditVirtualListener.class)
    public JAXBElement<String> createEditVirtualListenerPoolId(String value) {
        return new JAXBElement<String>(_EditVirtualListenerPoolId_QNAME, String.class, EditVirtualListener.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:didata.com:api:cloud:types", name = "clientClonePoolId", scope = EditVirtualListener.class)
    public JAXBElement<String> createEditVirtualListenerClientClonePoolId(String value) {
        return new JAXBElement<String>(_EditVirtualListenerClientClonePoolId_QNAME, String.class, EditVirtualListener.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:didata.com:api:cloud:types", name = "persistenceProfileId", scope = EditVirtualListener.class)
    public JAXBElement<String> createEditVirtualListenerPersistenceProfileId(String value) {
        return new JAXBElement<String>(_EditVirtualListenerPersistenceProfileId_QNAME, String.class, EditVirtualListener.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:didata.com:api:cloud:types", name = "fallbackPersistenceProfileId", scope = EditVirtualListener.class)
    public JAXBElement<String> createEditVirtualListenerFallbackPersistenceProfileId(String value) {
        return new JAXBElement<String>(_EditVirtualListenerFallbackPersistenceProfileId_QNAME, String.class, EditVirtualListener.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link List }{@code <}{@link String }{@code >}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:didata.com:api:cloud:types", name = "optimizationProfile", scope = EditVirtualListener.class)
    public JAXBElement<List<String>> createEditVirtualListenerOptimizationProfile(List<String> value) {
        return new JAXBElement<List<String>>(_EditVirtualListenerOptimizationProfile_QNAME, ((Class) List.class), EditVirtualListener.class, ((List<String> ) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:didata.com:api:cloud:types", name = "description", scope = EditNode.class)
    public JAXBElement<String> createEditNodeDescription(String value) {
        return new JAXBElement<String>(_EditVirtualListenerDescription_QNAME, String.class, EditNode.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:didata.com:api:cloud:types", name = "healthMonitorId", scope = EditNode.class)
    public JAXBElement<String> createEditNodeHealthMonitorId(String value) {
        return new JAXBElement<String>(_EditNodeHealthMonitorId_QNAME, String.class, EditNode.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:didata.com:api:cloud:types", name = "description", scope = EditPool.class)
    public JAXBElement<String> createEditPoolDescription(String value) {
        return new JAXBElement<String>(_EditVirtualListenerDescription_QNAME, String.class, EditPool.class, value);
    }

}
