//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.18 at 05:54:38 PM GMT 
//


package com.dimensiondata.cloud.client.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RulePlacementType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RulePlacementType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="position" use="required" type="{urn:didata.com:api:cloud:types}RulePositionType" /&gt;
 *       &lt;attribute name="relativeToRule" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RulePlacementType")
public class RulePlacementType {

    @XmlAttribute(name = "position", required = true)
    protected RulePositionType position;
    @XmlAttribute(name = "relativeToRule")
    protected String relativeToRule;

    /**
     * Gets the value of the position property.
     * 
     * @return
     *     possible object is
     *     {@link RulePositionType }
     *     
     */
    public RulePositionType getPosition() {
        return position;
    }

    /**
     * Sets the value of the position property.
     * 
     * @param value
     *     allowed object is
     *     {@link RulePositionType }
     *     
     */
    public void setPosition(RulePositionType value) {
        this.position = value;
    }

    /**
     * Gets the value of the relativeToRule property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelativeToRule() {
        return relativeToRule;
    }

    /**
     * Sets the value of the relativeToRule property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelativeToRule(String value) {
        this.relativeToRule = value;
    }

}
