//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.18 at 05:54:38 PM GMT 
//


package com.dimensiondata.cloud.client.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ServerType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ServerType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="operatingSystem" type="{urn:didata.com:api:cloud:types}OperatingSystemType"/&gt;
 *         &lt;element name="cpuCount" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="memoryGb" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="disk" maxOccurs="unbounded"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="scsiId" use="required" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                 &lt;attribute name="sizeGb" use="required" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                 &lt;attribute name="speed" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="state" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;choice&gt;
 *           &lt;element name="nic"&gt;
 *             &lt;complexType&gt;
 *               &lt;complexContent&gt;
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                   &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                   &lt;attribute name="privateIpv4" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                   &lt;attribute name="networkId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                   &lt;attribute name="networkName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                   &lt;attribute name="macAddress" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                   &lt;attribute name="state" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;/restriction&gt;
 *               &lt;/complexContent&gt;
 *             &lt;/complexType&gt;
 *           &lt;/element&gt;
 *           &lt;element name="networkInfo"&gt;
 *             &lt;complexType&gt;
 *               &lt;complexContent&gt;
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                   &lt;sequence&gt;
 *                     &lt;element name="primaryNic" type="{urn:didata.com:api:cloud:types}NicType"/&gt;
 *                     &lt;element name="additionalNic" type="{urn:didata.com:api:cloud:types}NicType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                   &lt;/sequence&gt;
 *                   &lt;attribute name="networkDomainId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;/restriction&gt;
 *               &lt;/complexContent&gt;
 *             &lt;/complexType&gt;
 *           &lt;/element&gt;
 *         &lt;/choice&gt;
 *         &lt;element name="backup" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;attribute name="assetId" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="servicePlan" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="state" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="monitoring" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;attribute name="monitoringId" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="servicePlan" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="state" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="softwareLabel" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="sourceImageId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="createTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="deployed" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="started" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="progress" type="{urn:didata.com:api:cloud:types}ProgressType" minOccurs="0"/&gt;
 *         &lt;element name="machineStatus" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="datacenterId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ServerType", propOrder = {
    "name",
    "description",
    "operatingSystem",
    "cpuCount",
    "memoryGb",
    "disk",
    "nic",
    "networkInfo",
    "backup",
    "monitoring",
    "softwareLabel",
    "sourceImageId",
    "createTime",
    "deployed",
    "started",
    "state",
    "progress",
    "machineStatus"
})
public class ServerType {

    @XmlElement(required = true)
    protected String name;
    protected String description;
    @XmlElement(required = true)
    protected OperatingSystemType operatingSystem;
    protected int cpuCount;
    protected int memoryGb;
    @XmlElement(required = true)
    protected List<ServerType.Disk> disk;
    protected ServerType.Nic nic;
    protected ServerType.NetworkInfo networkInfo;
    protected ServerType.Backup backup;
    protected ServerType.Monitoring monitoring;
    protected List<String> softwareLabel;
    protected String sourceImageId;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar createTime;
    protected boolean deployed;
    protected boolean started;
    @XmlElement(required = true)
    protected String state;
    protected ProgressType progress;
    protected List<ServerType.MachineStatus> machineStatus;
    @XmlAttribute(name = "id", required = true)
    protected String id;
    @XmlAttribute(name = "datacenterId", required = true)
    protected String datacenterId;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the operatingSystem property.
     * 
     * @return
     *     possible object is
     *     {@link OperatingSystemType }
     *     
     */
    public OperatingSystemType getOperatingSystem() {
        return operatingSystem;
    }

    /**
     * Sets the value of the operatingSystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperatingSystemType }
     *     
     */
    public void setOperatingSystem(OperatingSystemType value) {
        this.operatingSystem = value;
    }

    /**
     * Gets the value of the cpuCount property.
     * 
     */
    public int getCpuCount() {
        return cpuCount;
    }

    /**
     * Sets the value of the cpuCount property.
     * 
     */
    public void setCpuCount(int value) {
        this.cpuCount = value;
    }

    /**
     * Gets the value of the memoryGb property.
     * 
     */
    public int getMemoryGb() {
        return memoryGb;
    }

    /**
     * Sets the value of the memoryGb property.
     * 
     */
    public void setMemoryGb(int value) {
        this.memoryGb = value;
    }

    /**
     * Gets the value of the disk property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the disk property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDisk().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ServerType.Disk }
     * 
     * 
     */
    public List<ServerType.Disk> getDisk() {
        if (disk == null) {
            disk = new ArrayList<ServerType.Disk>();
        }
        return this.disk;
    }

    /**
     * Gets the value of the nic property.
     * 
     * @return
     *     possible object is
     *     {@link ServerType.Nic }
     *     
     */
    public ServerType.Nic getNic() {
        return nic;
    }

    /**
     * Sets the value of the nic property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServerType.Nic }
     *     
     */
    public void setNic(ServerType.Nic value) {
        this.nic = value;
    }

    /**
     * Gets the value of the networkInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ServerType.NetworkInfo }
     *     
     */
    public ServerType.NetworkInfo getNetworkInfo() {
        return networkInfo;
    }

    /**
     * Sets the value of the networkInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServerType.NetworkInfo }
     *     
     */
    public void setNetworkInfo(ServerType.NetworkInfo value) {
        this.networkInfo = value;
    }

    /**
     * Gets the value of the backup property.
     * 
     * @return
     *     possible object is
     *     {@link ServerType.Backup }
     *     
     */
    public ServerType.Backup getBackup() {
        return backup;
    }

    /**
     * Sets the value of the backup property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServerType.Backup }
     *     
     */
    public void setBackup(ServerType.Backup value) {
        this.backup = value;
    }

    /**
     * Gets the value of the monitoring property.
     * 
     * @return
     *     possible object is
     *     {@link ServerType.Monitoring }
     *     
     */
    public ServerType.Monitoring getMonitoring() {
        return monitoring;
    }

    /**
     * Sets the value of the monitoring property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServerType.Monitoring }
     *     
     */
    public void setMonitoring(ServerType.Monitoring value) {
        this.monitoring = value;
    }

    /**
     * Gets the value of the softwareLabel property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the softwareLabel property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSoftwareLabel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getSoftwareLabel() {
        if (softwareLabel == null) {
            softwareLabel = new ArrayList<String>();
        }
        return this.softwareLabel;
    }

    /**
     * Gets the value of the sourceImageId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceImageId() {
        return sourceImageId;
    }

    /**
     * Sets the value of the sourceImageId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceImageId(String value) {
        this.sourceImageId = value;
    }

    /**
     * Gets the value of the createTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreateTime() {
        return createTime;
    }

    /**
     * Sets the value of the createTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreateTime(XMLGregorianCalendar value) {
        this.createTime = value;
    }

    /**
     * Gets the value of the deployed property.
     * 
     */
    public boolean isDeployed() {
        return deployed;
    }

    /**
     * Sets the value of the deployed property.
     * 
     */
    public void setDeployed(boolean value) {
        this.deployed = value;
    }

    /**
     * Gets the value of the started property.
     * 
     */
    public boolean isStarted() {
        return started;
    }

    /**
     * Sets the value of the started property.
     * 
     */
    public void setStarted(boolean value) {
        this.started = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setState(String value) {
        this.state = value;
    }

    /**
     * Gets the value of the progress property.
     * 
     * @return
     *     possible object is
     *     {@link ProgressType }
     *     
     */
    public ProgressType getProgress() {
        return progress;
    }

    /**
     * Sets the value of the progress property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProgressType }
     *     
     */
    public void setProgress(ProgressType value) {
        this.progress = value;
    }

    /**
     * Gets the value of the machineStatus property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the machineStatus property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMachineStatus().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ServerType.MachineStatus }
     * 
     * 
     */
    public List<ServerType.MachineStatus> getMachineStatus() {
        if (machineStatus == null) {
            machineStatus = new ArrayList<ServerType.MachineStatus>();
        }
        return this.machineStatus;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the datacenterId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatacenterId() {
        return datacenterId;
    }

    /**
     * Sets the value of the datacenterId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatacenterId(String value) {
        this.datacenterId = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;attribute name="assetId" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="servicePlan" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="state" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Backup {

        @XmlAttribute(name = "assetId")
        protected String assetId;
        @XmlAttribute(name = "servicePlan", required = true)
        protected String servicePlan;
        @XmlAttribute(name = "state", required = true)
        protected String state;

        /**
         * Gets the value of the assetId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAssetId() {
            return assetId;
        }

        /**
         * Sets the value of the assetId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAssetId(String value) {
            this.assetId = value;
        }

        /**
         * Gets the value of the servicePlan property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getServicePlan() {
            return servicePlan;
        }

        /**
         * Sets the value of the servicePlan property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setServicePlan(String value) {
            this.servicePlan = value;
        }

        /**
         * Gets the value of the state property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getState() {
            return state;
        }

        /**
         * Sets the value of the state property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setState(String value) {
            this.state = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="scsiId" use="required" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *       &lt;attribute name="sizeGb" use="required" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *       &lt;attribute name="speed" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="state" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Disk {

        @XmlAttribute(name = "id", required = true)
        protected String id;
        @XmlAttribute(name = "scsiId", required = true)
        protected int scsiId;
        @XmlAttribute(name = "sizeGb", required = true)
        protected int sizeGb;
        @XmlAttribute(name = "speed", required = true)
        protected String speed;
        @XmlAttribute(name = "state", required = true)
        protected String state;

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the scsiId property.
         * 
         */
        public int getScsiId() {
            return scsiId;
        }

        /**
         * Sets the value of the scsiId property.
         * 
         */
        public void setScsiId(int value) {
            this.scsiId = value;
        }

        /**
         * Gets the value of the sizeGb property.
         * 
         */
        public int getSizeGb() {
            return sizeGb;
        }

        /**
         * Sets the value of the sizeGb property.
         * 
         */
        public void setSizeGb(int value) {
            this.sizeGb = value;
        }

        /**
         * Gets the value of the speed property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSpeed() {
            return speed;
        }

        /**
         * Sets the value of the speed property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSpeed(String value) {
            this.speed = value;
        }

        /**
         * Gets the value of the state property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getState() {
            return state;
        }

        /**
         * Sets the value of the state property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setState(String value) {
            this.state = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class MachineStatus {

        @XmlAttribute(name = "name", required = true)
        protected String name;
        @XmlAttribute(name = "value", required = true)
        protected String value;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;attribute name="monitoringId" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="servicePlan" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="state" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Monitoring {

        @XmlAttribute(name = "monitoringId")
        protected String monitoringId;
        @XmlAttribute(name = "servicePlan", required = true)
        protected String servicePlan;
        @XmlAttribute(name = "state", required = true)
        protected String state;

        /**
         * Gets the value of the monitoringId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMonitoringId() {
            return monitoringId;
        }

        /**
         * Sets the value of the monitoringId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMonitoringId(String value) {
            this.monitoringId = value;
        }

        /**
         * Gets the value of the servicePlan property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getServicePlan() {
            return servicePlan;
        }

        /**
         * Sets the value of the servicePlan property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setServicePlan(String value) {
            this.servicePlan = value;
        }

        /**
         * Gets the value of the state property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getState() {
            return state;
        }

        /**
         * Sets the value of the state property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setState(String value) {
            this.state = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="primaryNic" type="{urn:didata.com:api:cloud:types}NicType"/&gt;
     *         &lt;element name="additionalNic" type="{urn:didata.com:api:cloud:types}NicType" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *       &lt;attribute name="networkDomainId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "primaryNic",
        "additionalNic"
    })
    public static class NetworkInfo {

        @XmlElement(required = true)
        protected NicType primaryNic;
        protected List<NicType> additionalNic;
        @XmlAttribute(name = "networkDomainId", required = true)
        protected String networkDomainId;

        /**
         * Gets the value of the primaryNic property.
         * 
         * @return
         *     possible object is
         *     {@link NicType }
         *     
         */
        public NicType getPrimaryNic() {
            return primaryNic;
        }

        /**
         * Sets the value of the primaryNic property.
         * 
         * @param value
         *     allowed object is
         *     {@link NicType }
         *     
         */
        public void setPrimaryNic(NicType value) {
            this.primaryNic = value;
        }

        /**
         * Gets the value of the additionalNic property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the additionalNic property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAdditionalNic().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link NicType }
         * 
         * 
         */
        public List<NicType> getAdditionalNic() {
            if (additionalNic == null) {
                additionalNic = new ArrayList<NicType>();
            }
            return this.additionalNic;
        }

        /**
         * Gets the value of the networkDomainId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNetworkDomainId() {
            return networkDomainId;
        }

        /**
         * Sets the value of the networkDomainId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNetworkDomainId(String value) {
            this.networkDomainId = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="privateIpv4" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="networkId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="networkName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="macAddress" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="state" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Nic {

        @XmlAttribute(name = "id", required = true)
        protected String id;
        @XmlAttribute(name = "privateIpv4", required = true)
        protected String privateIpv4;
        @XmlAttribute(name = "networkId", required = true)
        protected String networkId;
        @XmlAttribute(name = "networkName", required = true)
        protected String networkName;
        @XmlAttribute(name = "macAddress")
        protected String macAddress;
        @XmlAttribute(name = "state", required = true)
        protected String state;

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the privateIpv4 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrivateIpv4() {
            return privateIpv4;
        }

        /**
         * Sets the value of the privateIpv4 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrivateIpv4(String value) {
            this.privateIpv4 = value;
        }

        /**
         * Gets the value of the networkId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNetworkId() {
            return networkId;
        }

        /**
         * Sets the value of the networkId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNetworkId(String value) {
            this.networkId = value;
        }

        /**
         * Gets the value of the networkName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNetworkName() {
            return networkName;
        }

        /**
         * Sets the value of the networkName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNetworkName(String value) {
            this.networkName = value;
        }

        /**
         * Gets the value of the macAddress property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMacAddress() {
            return macAddress;
        }

        /**
         * Sets the value of the macAddress property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMacAddress(String value) {
            this.macAddress = value;
        }

        /**
         * Gets the value of the state property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getState() {
            return state;
        }

        /**
         * Sets the value of the state property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setState(String value) {
            this.state = value;
        }

    }

}
